### ISSUE TITLE
[Fix] Stuck while joining a match

### ISSUE THREAD

**Issue by explowz** [nullworks/cathook-ipc-web-panel#14]
There's quite a simple solution to this. If queuing time > 25 minutes for more than 20 seconds send a «disconnect» command to the bot with that ID. Why wait 20 seconds? Because on map change the queue timer adds up the in-match time and usually results to something like 25-30-40 minutes until map changing is done and it reverts back to 0. By adding a check to see if it's been like that for more than 20 seconds (map should have plenty of time to load) you can determine that the bot is stuck while joining the match and not because of some other queuing issues. The panel already has a function to restart bots if a queue is taking longer than 20 minutes but for a stuck while joining match bug it doesn't seem to work. This also is a much better solution than just restarting the bot.

**Comment by explowz** [comment]
Why 25 minutes tho? Because sometimes bot don't get restarted immediately after they hit 20 minutes of queuing time. Sometimes it does, but sometimes it happens after 1-2 minutes. 25 minutes should make it very clear that the bot is definitely stuck upon joining the match and not something else.

**Comment by BenCat07** [comment]
The queueing time counts up but bot thinks it connected so the queue timer on cathook gets reset
